Repository SOPT-all/36-COLLABORATION-ANDROID-HYUNDAICARDDIVE, pull requests merged in 2025-05, with the labels that each got.

#6 [init] 이미지 세팅
  app/src/main/res/drawable/ic_culture_logo_culture.xml
  app/src/main/res/drawable/ic_culture_logo_davinci.xml
  app/src/main/res/drawable/ic_culture_logo_fan.xml
  app/src/main/res/drawable/ic_culture_logo_limited.xml
  app/src/main/res/drawable/ic_culture_logo_over.xml
  app/src/main/res/drawable/ic_culture_logo_super.xml
  app/src/main/res/drawable/ic_home_align_card_40.xml
  app/src/main/res/drawable/ic_home_align_slide_40.xml
  app/src/main/res/drawable/ic_home_bookmark_fill_white_40.xml
  app/src/main/res/drawable/ic_home_bookmark_white_40.xml
  app/src/main/res/drawable/ic_home_logo_article.xml
  app/src/main/res/drawable/ic_home_search_40.xml
  app/src/main/res/drawable/ic_introduce_back_10.xml
  app/src/main/res/drawable/ic_introduce_caution1_32.xml
  app/src/main/res/drawable/ic_introduce_caution2_32.xml
  app/src/main/res/drawable/ic_introduce_caution3_32.xml
  app/src/main/res/drawable/ic_introduce_caution4_32.xml
  app/src/main/res/drawable/ic_introduce_caution5_32.xml
  app/src/main/res/drawable/ic_introduce_caution6_32.xml
  app/src/main/res/drawable/ic_introduce_like_black_24.xml
  app/src/main/res/drawable/ic_introduce_like_fill_red_24.xml
  app/src/main/res/drawable/ic_introduce_review_24.xml
  app/src/main/res/drawable/ic_navi_culture_fill_black_36.xml
  app/src/main/res/drawable/ic_navi_culture_gray_36.xml
  app/src/main/res/drawable/ic_navi_home_fill_black_36.xml
  app/src/main/res/drawable/ic_navi_home_gray_36.xml
  app/src/main/res/drawable/ic_navi_profile_gray_36.xml
  app/src/main/res/drawable/ic_space_logo_artlib.xml
  app/src/main/res/drawable/ic_space_logo_card.xml
  app/src/main/res/drawable/ic_space_logo_cookinglib.xml
  app/src/main/res/drawable/ic_space_logo_designlib.xml
  app/src/main/res/drawable/ic_space_logo_iron.xml
  app/src/main/res/drawable/ic_space_logo_musiclib.xml
  app/src/main/res/drawable/ic_space_logo_red11.xml
  app/src/main/res/drawable/ic_space_logo_storage.xml
  app/src/main/res/drawable/ic_space_logo_understage.xml
  app/src/main/res/drawable/ic_space_logo_vinyl.xml
  app/src/main/res/drawable/ic_spaceculture_btn_space_more.xml
  app/src/main/res/drawable/ic_spaceculture_card_sapce_whatson_circle_7.xml
  app/src/main/res/drawable/ic_spaceculture_logo_space_culture.xml
  app/src/main/res/drawable/ic_spacedetail_book_28.xml
  app/src/main/res/drawable/ic_spacedetail_booksearch_28.xml
  app/src/main/res/drawable/ic_spacedetail_chevron_left_28.xml
  app/src/main/res/drawable/ic_spacedetail_reservation_28.xml
  app/src/main/res/drawable/ic_spacedetail_review_28.xml
  app/src/main/res/drawable/ic_spacedetail_space_28.xml
  app/src/main/res/drawable/img_introduce_btn_map.png
  app/src/main/res/drawable/img_introduce_congestion_graph.png
  app/src/main/res/drawable/img_introduce_map.png
  app/src/main/res/drawable/img_spacedetail_barcord.png
  app/src/main/res/drawable/img_spacedetail_logo_hdc_balck.png
  app/src/main/res/drawable/img_spacedetail_logo_hdc_white.png
Labels: ⚙️ Init, 💙 승준

#10 [feat] 상세 화면 공통 컴포넌트 제작
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/DetailMenuItem.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailDescriptionSection.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailTabBar.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💙 UI, 💛 혜정

#14 [init] 확장함수 세팅
  app/src/main/java/org/sopt/hyundaicarddive/HyunDaiCardDiveApplication.kt
  app/src/main/java/org/sopt/hyundaicarddive/core/util/ContextExt.kt
  app/src/main/java/org/sopt/hyundaicarddive/core/util/DummyExt.kt
  app/src/main/java/org/sopt/hyundaicarddive/core/util/ModifierExt.kt
Labels: ⚙️ Init, 🖤 민서

#13 [feat] 공간-문화, 공간 소개 공통 컴포넌트 구현
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/component/SpaceBaseButton.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/spaceandculture/component/SpaceAndCultureHeader.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💙 UI, 💙 승준

#17 [feat] 홈 컴포넌트, 탑바 공통 컴포넌트 구현
  app/src/main/java/org/sopt/hyundaicarddive/core/component/DummyComponent.kt
  app/src/main/java/org/sopt/hyundaicarddive/core/component/TopBar.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/SortOptionType.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/TopBarType.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/component/CategoryBar.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/component/SortOptionBar.kt
Labels: ✨ Feat, 💙 UI, 🖤 민서

#19 [feat] 홈 뷰 UI 구현
  app/src/main/java/org/sopt/hyundaicarddive/presentation/model/DummyModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/model/HomeListModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/component/CategoryBar.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/component/HomeCardList.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/home/component/HomeSlideList.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/main/MainNavHost.kt
Labels: ✨ Feat, 💙 UI, 🖤 민서

#21 [feat] 디테일 뷰 UI 구현
  app/src/main/java/org/sopt/hyundaicarddive/presentation/model/DetailModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/DetailScreen.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailDescriptionSection.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailPager.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailTabBar.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/navigation/DetailNavigation.kt
  app/src/main/java/org/sopt/hyundaicarddive/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💙 UI, 💛 혜정

#26 [feat] 공간 소개 뷰 UI 구현
  app/src/main/java/org/sopt/hyundaicarddive/presentation/model/SpaceModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/SpaceCautionGridItem.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/type/TopBarType.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/main/MainNavHost.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/SpaceScreen.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/SpaceViewModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/component/SpaceBaseButton.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/component/SpaceCautionGrid.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/component/SpaceReviewPager.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/navigation/SpaceNavigation.kt
  app/src/main/res/drawable/ic_introduce_back_10.xml
  app/src/main/res/drawable/ic_introduce_chevron_left_28.xml
  app/src/main/res/drawable/ic_introduce_chevron_right_7.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💙 UI, 💙 승준

#28 [Feat] 디테일 뷰 API 연결
  app/src/main/java/org/sopt/hyundaicarddive/data/mapper/todomain/DetailResponseMapper.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/datasource/DetailRemoteDataSource.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/datasourceimpl/DetailRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/dto/response/DetailResponseDto.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/service/DetailService.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/repositoryimpl/DetailRepositoryImpl.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/DataSourceModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/RepositoryModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/ServiceModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/UseCaseModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/model/DetailData.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/repository/DetailRepository.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/usecase/DetailUseCase.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/DetailScreen.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/DetailViewModel.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/detail/component/DetailPager.kt
Labels: ✨ Feat, 💻 서버 통신, 💛 혜정

#32 [feat] 공간 소개 뷰 API 연결
  app/src/main/java/org/sopt/hyundaicarddive/data/mapper/todomain/SpaceResponseMapper.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/datasource/SpaceRemoteDataSource.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/datasourceimpl/SpaceRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/dto/response/SpaceResponseDto.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/remote/service/SpaceService.kt
  app/src/main/java/org/sopt/hyundaicarddive/data/repositoryimpl/SpaceRepositoryImpl.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/DataSourceModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/RepositoryModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/ServiceModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/di/UseCaseModule.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/model/SpaceData.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/repository/SpaceRepository.kt
  app/src/main/java/org/sopt/hyundaicarddive/domain/usecase/SpaceUseCase.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/main/MainBottomBar.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/SpaceScreen.kt
  app/src/main/java/org/sopt/hyundaicarddive/presentation/ui/space/SpaceViewModel.kt
Labels: ✨ Feat, 💻 서버 통신, 💙 승준
